// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using volgatech_server.Context;

#nullable disable

namespace volgatech_server.Migrations
{
    [DbContext(typeof(LaboratoryDbContext))]
    [Migration("20240526182458_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("volgatech_server.Context.Models.AccessToken", b =>
                {
                    b.Property<int>("AccessTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AccessTokenId"));

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AccessTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("AccessTokens");
                });

            modelBuilder.Entity("volgatech_server.Context.Models.Bundle", b =>
                {
                    b.Property<int>("BundleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BundleId"));

                    b.Property<int>("BundleInfoId")
                        .HasColumnType("int");

                    b.Property<int?>("StorageId")
                        .HasColumnType("int");

                    b.HasKey("BundleId");

                    b.HasIndex("BundleInfoId");

                    b.HasIndex("StorageId");

                    b.ToTable("Bundles");
                });

            modelBuilder.Entity("volgatech_server.Context.Models.BundleInfo", b =>
                {
                    b.Property<int>("BundleInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BundleInfoId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("BundleInfoId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BundleInfos");
                });

            modelBuilder.Entity("volgatech_server.Context.Models.BundleItem", b =>
                {
                    b.Property<int>("BundleItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BundleItemId"));

                    b.Property<int?>("BundleId")
                        .HasColumnType("int");

                    b.Property<int>("BundleItemInfoId")
                        .HasColumnType("int");

                    b.Property<int>("FunctionalType")
                        .HasColumnType("int");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("StorageId")
                        .HasColumnType("int");

                    b.HasKey("BundleItemId");

                    b.HasIndex("BundleId");

                    b.HasIndex("BundleItemInfoId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StorageId");

                    b.ToTable("BundleItems");
                });

            modelBuilder.Entity("volgatech_server.Context.Models.BundleItemInfo", b =>
                {
                    b.Property<int>("BundleItemInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("BundleItemInfoId"));

                    b.Property<int?>("BundleInfoId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("BundleItemInfoId");

                    b.HasIndex("BundleInfoId");

                    b.ToTable("BundleItemInfos");
                });

            modelBuilder.Entity("volgatech_server.Context.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("volgatech_server.Context.Models.File", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("FileId"));

                    b.Property<int>("ObjectId")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("FileId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("volgatech_server.Context.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ResponsibleId")
                        .HasMaxLength(255)
                        .HasColumnType("int");

                    b.HasKey("ProjectId");

                    b.HasIndex("ResponsibleId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("volgatech_server.Context.Models.Responsible", b =>
                {
                    b.Property<int>("ResponsibleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ResponsibleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("ResponsibleId");

                    b.ToTable("Responsibles");
                });

            modelBuilder.Entity("volgatech_server.Context.Models.Storage", b =>
                {
                    b.Property<int>("StorageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StorageId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("StorageId");

                    b.ToTable("Storages");
                });

            modelBuilder.Entity("volgatech_server.Context.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Login")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("volgatech_server.Context.Models.AccessToken", b =>
                {
                    b.HasOne("volgatech_server.Context.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("volgatech_server.Context.Models.Bundle", b =>
                {
                    b.HasOne("volgatech_server.Context.Models.BundleInfo", "BundleInfo")
                        .WithMany("Bundles")
                        .HasForeignKey("BundleInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("volgatech_server.Context.Models.Storage", "Storage")
                        .WithMany()
                        .HasForeignKey("StorageId");

                    b.Navigation("BundleInfo");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("volgatech_server.Context.Models.BundleInfo", b =>
                {
                    b.HasOne("volgatech_server.Context.Models.Category", "Category")
                        .WithMany("BundleInfos")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("volgatech_server.Context.Models.BundleItem", b =>
                {
                    b.HasOne("volgatech_server.Context.Models.Bundle", "Bundle")
                        .WithMany("BundleItems")
                        .HasForeignKey("BundleId");

                    b.HasOne("volgatech_server.Context.Models.BundleItemInfo", "BundleItemInfo")
                        .WithMany("BundleItems")
                        .HasForeignKey("BundleItemInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("volgatech_server.Context.Models.Project", "Project")
                        .WithMany("BundleItems")
                        .HasForeignKey("ProjectId");

                    b.HasOne("volgatech_server.Context.Models.Storage", "Storage")
                        .WithMany()
                        .HasForeignKey("StorageId");

                    b.Navigation("Bundle");

                    b.Navigation("BundleItemInfo");

                    b.Navigation("Project");

                    b.Navigation("Storage");
                });

            modelBuilder.Entity("volgatech_server.Context.Models.BundleItemInfo", b =>
                {
                    b.HasOne("volgatech_server.Context.Models.BundleInfo", "BundleInfo")
                        .WithMany()
                        .HasForeignKey("BundleInfoId");

                    b.Navigation("BundleInfo");
                });

            modelBuilder.Entity("volgatech_server.Context.Models.Project", b =>
                {
                    b.HasOne("volgatech_server.Context.Models.Responsible", "Responsible")
                        .WithMany()
                        .HasForeignKey("ResponsibleId");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("volgatech_server.Context.Models.Bundle", b =>
                {
                    b.Navigation("BundleItems");
                });

            modelBuilder.Entity("volgatech_server.Context.Models.BundleInfo", b =>
                {
                    b.Navigation("Bundles");
                });

            modelBuilder.Entity("volgatech_server.Context.Models.BundleItemInfo", b =>
                {
                    b.Navigation("BundleItems");
                });

            modelBuilder.Entity("volgatech_server.Context.Models.Category", b =>
                {
                    b.Navigation("BundleInfos");
                });

            modelBuilder.Entity("volgatech_server.Context.Models.Project", b =>
                {
                    b.Navigation("BundleItems");
                });
#pragma warning restore 612, 618
        }
    }
}
